### ISSUE TITLE
Feature Request: Ability to Resize Graph Font Sizes

### ISSUE THREAD

**Issue by darethehair** [briot/geneapro#15]
In some cases, the font size used for display graphs is a nice visual size, but the label text 'bumps into' the container boxes.  In other cases, the font is automatically made too tiny to view (perhaps the font size should be kept the same for the entire graph, and let the vertical/horizontal spacing take care of the display?).

**Comment by briot** [comment]
I think the font are correct in the graphs now. You cannot configure the font size, but you can zoom in the graph if you need to make fonts larger or smaller
