### ISSUE TITLE
Feature Request: Surname +Given Name Sort on Show All Persons List

### ISSUE THREAD

**Issue by darethehair** [briot/geneapro#19]
It appears as though the default sort order on the 'Show all persons' list is 'surname', which is perfectly valid and good.  However, it probably would be good if the 2nd column (i.e. 'given name') would automatically be the 2nd sort column when that is done e.g. so that 'Darren Enns' is display _after_ 'Bob Enns'.

**Comment by briot** [comment]
For now at least, I have changed the handling of names to match what the Gedcom format describes: the display name for a person should be exactly the one exported in Gedcom. Any decomposition between First name and Surname, and others, is purely for filtering and sorting.
The result is that now I have a single "Name" column on the "All Persons" list. Not as good for sorting, but the filtering works great and I expect people would rather use it.

The idea is that when one can finally edit via the GUI, we can chose what display name to use for a person. In the long term, we can have a system that knows how to combine the name pieces (first name, title, surname,...) in the right order for a given place and time, to generate those display names.
