### ISSUE TITLE
setup.sh explicitly requires nodejs v7.10.1, but README.md states 'nodejs >= 7.7.3'

### ISSUE THREAD

**Issue by changeling** [briot/geneapro#23]
setup.sh fails on any version of nodejs other than v7.10.1, but the docs say that any version >= v7.7.3 is acceptable.

**Comment by briot** [comment]
> setup.sh fails on any version of nodejs other than v7.10.1, but the docs say that any version >= v7.7.3 is acceptable.


I’ll take a look. This is mostly a matter of adjusting setup.sh, because in practice geneapro
doesn’t depend on a particular version of nodejs I believe, except indirectly because some of
its own dependencies (react-create-app in particular) do.

**Comment by changeling** [comment]
I simply replaced v7.10.1 with my installed v8.11.1 in my local setup.sh. Everything seems ok so far.

Thanks for such a rapid response.
