### ISSUE TITLE
Fresh install followed by ./setup.sh yields a warning that ajv-keywords@3.1.0 requires ajv@^6.0.0.

### ISSUE THREAD

**Issue by changeling** [briot/geneapro#30]
Running `setup.sh` on a fresh `geneapro` directory gives the following warning:

```
npm WARN ajv-keywords@3.1.0 requires a peer of ajv@^6.0.0 but none is installed. You must install peer dependencies yourself.
```

**Comment by briot** [comment]
Wow, I have no idea what ajv-keywords is about, nor what part of node needs it.
But if that's a warning, I think it can simply be ignored

**Comment by briot** [comment]
Given later exchanges, seems that things are working fine on your side now ?

**Comment by changeling** [comment]
Ha! Yep!
