### ISSUE TITLE
Failure upon launch with fresh install.

### ISSUE THREAD

**Issue by changeling** [briot/geneapro#35]
Receiving this when browser launches. I've tried node from `7.7.2` to `v10.13.0`, clearing everything to scratch each time:

```
Failed to compile
./src/Server/Stats.tsx 18:16
Module parse failed: Identifier 'fetchCountFromServer' has already been declared (18:16)
You may need an appropriate loader to handle this file type.
|     });
| }
> export function fetchCountFromServer() {
|     return window.fetch('/data/stats/count')
|         .then(resp => {
This error occurred during the build time and cannot be dismissed.
```

**Comment by briot** [comment]
Wow, you’re fast on the uptake, I just uploaded the new version :-)

> Receiving this when browser launches. I've tried node from 7.7.2 to v10.13.0, clearing everything to scratch each time:

I just tried the following

    \rm -rf node_modules pakage.json-lock
    npm run build

and everything worked fine. That generated a new slightly different package.json-lock, so I’ll upload
this one.

I am on OSX, using

  nodejs8 @8.12.0_0 (active)
  npm6 @6.4.1_0 (active)



> 
> Failed to compile
> ./src/Server/Stats.tsx 18:16
> Module parse failed: Identifier 'fetchCountFromServer' has already been declared (18:16)
> You may need an appropriate loader to handle this file type.
> |     });
> | }
> > export function fetchCountFromServer() {
> |     return window.fetch('/data/stats/count')
> |         .then(resp => {
> This error occurred during the build time and cannot be dismissed.


The error seems incorrect at first sight, though it might be the result of some other issue.

**Comment by changeling** [comment]
Ha! Not fast enough! I grabbed the code just _before_ your update! :) And yes, that update fixed that problem. :)
