### ISSUE TITLE
setup.sh for distribution.

### ISSUE THREAD

**Issue by changeling** [briot/geneapro#36]
The `setup.sh` script is calling for deps that aren't relevant except to development. In addition, `pyinstaller` is causing a failure on my end that prevents the python session from continuing:

    pip install django==1.10.6 pillow pylint pylint-django pep8 autopep8 grandalf \
       django-prepared-query cprofilev pyinstaller appdirs

I've shortened the lines on my local copy to:

    pip install django==1.10.6 pillow grandalf django-prepared-query appdirs

And all is right with the world. (Well, maybe not the world. The code.)

**Comment by changeling** [comment]
I've created https://github.com/briot/geneapro/pull/40 for this.

**Comment by briot** [comment]
merged
