### ISSUE TITLE
Parser fails on invalid '1 DEAT 2 DATE Deceased' entry.

### ISSUE THREAD

**Issue by changeling** [briot/geneapro#39]
There's an invalid pattern that shows up occasionally in data from different sources:

```
1 DEAT
2 DATE Deceased
```

This triggers `parse Unexpected Exception during parsing`.

It's probably best to simply skip any `2 DATE Deceased`. It's simply a bad entry without any real DATE information.

**Comment by briot** [comment]
> There's an invalid pattern that shows up occasionally in data from different sources:
> 
> 1 DEAT
> 2 DATE Deceased
> 
> This triggers parse Unexpected Exception during parsing.
> 
> It's probably best to simply skip any 2 DATE Deceased. It's simply a bad entry without any real DATE information.


I don’t want to just skip data. So the date should just be recorded as such. Sure, it is invalid,
but generaprove is in fact meant to store any data as-is, and try to compute a yyyy-mm-dd from
it when possible, for sorting and comparison purposes. Likely what is failing here is that
conversion, and that should not happen.

I’ll try and reproduce, thanks for the report

Emmanuel

**Comment by changeling** [comment]
Actually, I edited to the title of this issue after digging through a bit. It seems to be the `event` handling of invalid dates. And I appreciate keeping the data. That's good policy.

As is confirming what an issue actually is before reporting a problem. :( :) I need to be more careful.

**Comment by briot** [comment]
This issue is now fixed, thanks for the report !

**Comment by changeling** [comment]
Wow, you're quick! Great and thanks! Hope I'm not becoming the annoying kid
in class constantly pointing out problems.

**Comment by briot** [comment]
> Wow, you're quick! Great and thanks! Hope I'm not becoming the annoying kid
> in class constantly pointing out problems.


That’s really a one-developer, half-a-user project so far, so feedback is more than
welcome. Likely it will never be a fully developed tool, for lack of time, but I think
there are some interesting ideas and I want to fix simple things like this so that
people get to play with it.

At some point, I need to understand better how I can distribute a pre-compiled
version for non-developers who might not have python on their machines…

Please keep testing and sending bug reports !

Emmanuel

**Comment by changeling** [comment]
This has become my goto, playtime project. I'll definitely keep testing and
when I have a bit of time, I'll help you with the packaging.

It's good to see you back. :)
