### ISSUE TITLE
Zoom is not zooming.

### ISSUE THREAD

**Issue by changeling** [briot/geneapro#62]
On a MacBook Pro, zooming of the various charts was working with two-finger gestures on the trackpad (I assume it's read as a mouse-wheel. With the latest changes, that is no longer happening.

Also, is there a way to zoom with a mouse that has no wheel? The code doesn't seem to have this, but my javascript-foo is weak, so I thought I'd ask.

**Comment by briot** [comment]
> On a MacBook Pro, zooming of the various charts was working with two-finger gestures on the trackpad (I assume it's read as a mouse-wheel. With the latest changes, that is no longer happening.

I have the same machine, and everything works for me. Better than before in fact, since scrolling on the trackpad with two fingers
used to also scroll the page, but I have no set the height of elements so that that gesture really only modifies the zoom.

The pinch gesture also works for zooming in and out...

> Also, is there a way to zoom with a mouse that has no wheel? The code doesn't seem to have this, but my javascript-foo is weak, so I thought I'd ask.

A mouse with no wheel ? Hum, I would have to look hard to find one :-)
Liikely unsupported indeed

**Comment by changeling** [comment]
Can you test with Firefox v66.0.2? My copy updated yesterday, and there are a couple or three things in the release notes that could be at fault.

See https://www.mozilla.org/en-US/firefox/66.0.2/releasenotes/.

I just tried in Chrome v73.0.3683.86 and yep,  it works, and is smooth as silk.

**Comment by briot** [comment]
> Can you test with Firefox v66.0.2? My copy updated yesterday, and there are a couple or three things in the release notes that could be at fault.
> 
> See https://www.mozilla.org/en-US/firefox/66.0.2/releasenotes/.
> 
> I just tried in Chrome v73.0.3683.86 and yep, it works, and is smooth as silk.


Indeed fails with Firefox 66… Looking into that

**Comment by changeling** [comment]
> A mouse with no wheel ? Hum, I would have to look hard to find one :-) Liikely unsupported indeed

Ha! Here's a photo of my testing/emergency mouse. I use it for UX/UI testing, and occasionally if my trackpad has a problem. Perhaps it looks familiar? :D:
![IMG_0006](https://user-images.githubusercontent.com/400894/55642946-7c623580-5797-11e9-9bf4-445ba4dab007.png)

On a serious note, you might consider a key/mouse combination option for zooming. Perhaps control + mouse-click-drag.

Firefox works well now, and is smoother now.

**Comment by changeling** [comment]
Out of curiosity, have you tried the NF Z71-300 keyboard layout? Any thoughts? I'm wondering whether such a big change is going to catch on.
